import Head from 'next/head';
import Typography from '@mui/material/Typography';

export default function About() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography variant='h1'>About page content - h1</Typography>
            <Typography variant='h2'>About page content - h2</Typography>
            <Typography variant='h3'>About page content - h3</Typography>
            <Typography variant='h4'>About page content - h4</Typography>
            <Typography variant='h5'>About page content - h5</Typography>
            <Typography variant='h6'>About page content - h6</Typography>
            <Typography variant='subtitle1'>About page content - subtitle1</Typography>
            <Typography variant='subtitle2'>About page content - subtitle2</Typography>
            <Typography variant='body1'>About page content - body1</Typography>
            <Typography variant='body2'>About page content - body2</Typography>
            <Typography>About page content - variant not given (body1 default)</Typography>
        </div>
    )
}
