import { useState } from 'react';
import Head from 'next/head';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import StaffTab from '../components/admin/staff/StaffTab';
import Tab from '@mui/material/Tab';
import Tabs from '@mui/material/Tabs';
import TabPanel from '../components/layout/TabPanel';
import Typography from '@mui/material/Typography';

export default function Admin() {

    const [activeTabIndex, setActiveTabIndex] = useState(0);
    
    function a11yProps(index) {
        return {
            id: `tab-${index}`,
            'aria-controls': `tabpanel-${index}`,
        };
    }

    const handleChange = (event, newActiveTabIndex) => {
        setActiveTabIndex(newActiveTabIndex);
    };  

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography component="h1" variant="h4">
                Admin Panel
            </Typography>
            <Box sx={{pt: 1 }}>
                <Paper elevation={3}>
                    <Box sx={{ width: '100%' }}>
                        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                            <Tabs value={activeTabIndex} onChange={handleChange} aria-label="basic tabs example">
                                <Tab label="Staff" {...a11yProps(0)} />
                                <Tab label="Item Two" {...a11yProps(1)} />
                                <Tab label="Item Three" {...a11yProps(2)} />
                            </Tabs>
                        </Box>
                        <TabPanel activeTabIndex={activeTabIndex} index={0}>
                            <StaffTab />
                        </TabPanel>
                        <TabPanel activeTabIndex={activeTabIndex} index={1}>
                            <Typography>Item Two</Typography>
                        </TabPanel>
                        <TabPanel activeTabIndex={activeTabIndex} index={2}>
                            <Typography>Item Three</Typography>
                        </TabPanel>
                    </Box>
                </Paper>
            </Box>
        </div>
    )
}
