import Box from '@mui/material/Box';
import Head from 'next/head';
import Typography from '@mui/material/Typography';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{ pt: 2, px: 3 }}>
                <Typography component="h1" variant='h4'>Header</Typography>
                <Typography>Home page content - variant not given (body1 default)</Typography>
            </Box>
        </div>
    )
}
