import Head from 'next/head';
import Typography from '@mui/material/Typography';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography variant='h1'>Home page content - h1</Typography>
            <Typography variant='h2'>Home page content - h2</Typography>
            <Typography variant='h3'>Home page content - h3</Typography>
            <Typography variant='h4'>Home page content - h4</Typography>
            <Typography variant='h5'>Home page content - h5</Typography>
            <Typography variant='h6'>Home page content - h6</Typography>
            <Typography variant='subtitle1'>Home page content - subtitle1</Typography>
            <Typography variant='subtitle2'>Home page content - subtitle2</Typography>
            <Typography variant='body1'>Home page content - body1</Typography>
            <Typography variant='body2'>Home page content - body2</Typography>
            <Typography>Home page content - variant not given (body1 default)</Typography>
        </div>
    )
}
