import { useState } from 'react';
import CustomSnackbar from '../components/layout/CustomSnackbar';
import Head from 'next/head';
import Schedule from '../components/schedule/Schedule';

export default function Calendar() {

    const [snackbarOpen, setSnackbarOpen] = useState(false);
    const [snackbarSeverity, setSnackbarSeverity] = useState("");
    const [snackbarMessage, setSnackbarMessage] = useState("");

    const snackbarSendMessage = (options) => {
        setSnackbarSeverity(options.severity || 'info');
        setSnackbarMessage(options.message || '');
        setSnackbarOpen(true);
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Schedule snackbarSendMessage={snackbarSendMessage}/>
            <CustomSnackbar
                openState={snackbarOpen}
                setOpenState={setSnackbarOpen}
                severity={snackbarSeverity}
                message={snackbarMessage}
            />
        </div>
    )
}
