import { MODE_ADD } from '../lib/constants';
import { useState } from 'react';
import Box from '@mui/material/Box';
import CustomSnackbar from '../components/layout/CustomSnackbar';
import Head from 'next/head';
import DayRoomSchedule from '../components/schedule/DayRoomSchedule';
import DayStaffSchedule from '../components/schedule/DayStaffSchedule';
import RoomSchedule from '../components/schedule/RoomSchedule';
import ScheduleModal from '../components/schedule/ScheduleModal';
import StaffSchedule from '../components/schedule/StaffSchedule';
import Tab from '@mui/material/Tab';
import Tabs from '@mui/material/Tabs';
import TabPanel from '../components/layout/TabPanel';

export default function Calendar() {

    const [activeTabIndex, setActiveTabIndex] = useState(0);

    const [snackbarOpen, setSnackbarOpen] = useState(false);
    const [snackbarSeverity, setSnackbarSeverity] = useState("");
    const [snackbarMessage, setSnackbarMessage] = useState("");

    const snackbarSendMessage = (options) => {
        setSnackbarSeverity(options.severity || 'info');
        setSnackbarMessage(options.message || '');
        setSnackbarOpen(true);
    }

    const [modalOpen, setModalOpen] = useState(false);
    const [modalMode, setModalMode] = useState(MODE_ADD);
    const [modalDay, setModalDay] = useState('');
    const [modalStart, setModalStart] = useState('');
    const [modalEnd, setModalEnd] = useState('');
    const [modalStaff, setModalStaff] = useState('');
    const [modalLesson, setModalLesson] = useState('');
    const [modalRoom, setModalRoom] = useState('');
    const [modalScheduleId, setModalScheduleId] = useState('');

    const handleModalClose = () => {
        setModalOpen(false);
        // setLessonName('');
        // setLessonColor('');
        // setLessonId('');
    };

    const showModal = () => {
        setModalOpen(true);
    };

    function a11yProps(index) {
        return {
            id: `tab-${index}`,
            'aria-controls': `tabpanel-${index}`,
        };
    }

    const handleTabChange = (event, newActiveTabIndex) => {
        setActiveTabIndex(newActiveTabIndex);
    };  


    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box sx={{ width: '100%' }}>
                <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                    <Tabs value={activeTabIndex} onChange={handleTabChange} aria-label="basic tabs example">
                        <Tab label="By Room" {...a11yProps(0)} />
                        <Tab label="By Staff" {...a11yProps(1)} />
                        <Tab label="By Day & Room" {...a11yProps(2)} />
                        <Tab label="By Day & Staff" {...a11yProps(3)} />
                    </Tabs>
                </Box>
                <TabPanel activeTabIndex={activeTabIndex} index={0}>
                    <RoomSchedule
                        setModalMode={setModalMode}
                        showModal={showModal} 
                        snackbarSendMessage={snackbarSendMessage}
                    />
                </TabPanel>
                <TabPanel activeTabIndex={activeTabIndex} index={1}>
                    <StaffSchedule
                        setModalMode={setModalMode}
                        showModal={showModal}
                        snackbarSendMessage={snackbarSendMessage}
                    />
                </TabPanel>
                <TabPanel activeTabIndex={activeTabIndex} index={2}>
                    <DayRoomSchedule
                        setModalMode={setModalMode}
                        showModal={showModal} 
                        snackbarSendMessage={snackbarSendMessage}
                    />
                </TabPanel>
                <TabPanel activeTabIndex={activeTabIndex} index={3}>
                    <DayStaffSchedule
                        setModalMode={setModalMode}
                        showModal={showModal}
                        snackbarSendMessage={snackbarSendMessage}
                    />
                </TabPanel>
                <CustomSnackbar
                    openState={snackbarOpen}
                    setOpenState={setSnackbarOpen}
                    severity={snackbarSeverity}
                    message={snackbarMessage}
                />
                <ScheduleModal
                    closeHandler={handleModalClose}
                    modalOpen={modalOpen}
                    modalMode={modalMode}
                    snackbarUse={snackbarSendMessage}
                    modalDay={modalDay}
                    setModalDay={setModalDay}
                    modalStart={modalStart}
                    setModalStart={setModalStart}
                    modalEnd={modalEnd}
                    setModalEnd={setModalEnd}
                    modalStaff={modalStaff}
                    setModalStaff={setModalStaff}
                    modalLesson={modalLesson}
                    setModalLesson={setModalLesson}
                    modalRoom={modalRoom}
                    setModalRoom={setModalRoom}
                    modalScheduleId={modalScheduleId}
                    setModalScheduleId={setModalScheduleId}
                />
            </Box>
        </div>
    )
}
